language: objective-c

branches:
 only:
 - master

xcode_project: DyPhotos.xcodeproj
xcode_scheme: DyPhotosTests
osx_image: xcode8.1
xcode_sdk: iphonesimulator10.1

script:
- xcodebuild clean build test -project DyPhotos.xcodeproj -scheme DyPhotos -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1'